export default [
  {
    img: "Blue Chopped Ombré Hoodie.png",
    title: "Blue Chopped Ombré Hoodie",
    category: "men",
    price: 450,
    avail: true,
  },
  {
    img: "Blue Gradient Floral Shirt.png",
    title: "Blue Gradient Floral Shirt",
    category: "men",
    price: 300,
    avail: true,
  },
  {
    img: "Brown Coach Jacket.png",
    title: "Brown Coach Jacket",
    category: "men",
    price: 520,
    avail: true,
  },
  {
    img: "Navy Dipped Jacket.png",
    title: "Navy Dipped Jacket",
    category: "men",
    price: 460,
    avail: true,
  },
  {
    img: "White & Black Jacquard Knit Sweatshirt.png",
    title: "White & Black Jacquard Knit Sweatshirt",
    category: "men",
    price: 320,
    avail: true,
  },
  {
    img: "Black Studded Hoodie.png",
    title: "Black Studded Hoodie",
    category: "men",
    price: 370,
    avail: true,
  },
  {
    img: "White & Blue Printing Jacket.png",
    title: "White & Blue Printing Jacket",
    category: "men",
    price: 750,
    avail: true,
  },
  {
    img: "Khaki Chicago Sweatshirt.png",
    title: "Khaki Chicago Sweatshirt",
    category: "men",
    price: 290,
    avail: true,
  },
  {
    img: "Orange Skate Quick Release Trousers.png",
    title: "Orange Skate Quick Release Trousers",
    category: "men",
    price: 400,
    avail: true,
  },
  {
    img: "Multicolor Printed Trousers.png",
    title: "Multicolor Printed Trousers",
    category: "men",
    price: 700,
    avail: true,
  },
  {
    img: "Gray Lightweight Cargo Pants.png",
    title: "Gray Lightweight Cargo Pants",
    category: "men",
    price: 350,
    avail: true,
  },
  {
    img: "White John Jeans.png",
    title: "White John Jeans",
    category: "men",
    price: 500,
    avail: true,
  },

  {
    img: "Beige Jumbo GG Chevron Web Jacket.png",
    title: "Beige Jumbo GG Chevron Web Jacket",
    category: "women",
    price: 1200,
    avail: true,
  },
  {
    img: "Beige Raglan Hoodie.png",
    title: "Beige Raglan Hoodie",
    category: "women",
    price: 640,
    avail: true,
  },
  {
    img: "Blue Printed Denim Jacket.png",
    title: "Blue Printed Denim Jacket",
    category: "women",
    price: 430,
    avail: true,
  },
  {
    img: "Brown Dipped Jacket.png",
    title: "Brown Dipped Jacket",
    category: "women",
    price: 600,
    avail: true,
  },
  {
    img: "Pink Zip Bomber Jacket.png",
    title: "Pink Zip Bomber Jacket",
    category: "women",
    price: 670,
    avail: true,
  },
  {
    img: "Green Embroidered Hoodie.png",
    title: "Green Embroidered Hoodie",
    category: "women",
    price: 410,
    avail: true,
  },

  {
    img: "Pink Unicorn Hoodie.png",
    title: "Pink Unicorn Hoodie",
    category: "women",
    price: 700,
    avail: true,
  },
  {
    img: "White Embroidered Sweatshirt.png",
    title: "White Embroidered Sweatshirt",
    category: "women",
    price: 490,
    avail: true,
  },
  {
    img: "Pink Press-Stud Vest.png",
    title: "Pink Press-Stud Vest",
    category: "women",
    price: 380,
    avail: true,
  },
  {
    img: "Blue Pocket Stamped Jeans.png",
    title: "Blue Pocket Stamped Jeans",
    category: "women",
    price: 500,
    avail: true,
  },
  {
    img: "Brown Creased Trousers.png",
    title: "Brown Creased Trousers",
    category: "women",
    price: 720,
    avail: true,
  },
  {
    img: "White Super High Workwear Jeans.png",
    title: "White Super High Workwear Jeans",
    category: "women",
    price: 850,
    avail: true,
  },

  {
    img: "Beige GG Supreme Ophidia Cosmetic Case.png",
    title: "Beige GG Supreme Ophidia Cosmetic Case",
    category: "acc",
    price: 800,
    avail: true,
  },
  {
    img: "Blue Dive Watch.png",
    title: "Blue Dive Watch",
    category: "acc",
    price: 340,
    avail: true,
  },
  {
    img: "Two-Pack Purple & White Trolls Socks.png",
    title: "Two-Pack Purple & White Trolls Socks",
    category: "acc",
    price: 280,
    avail: true,
  },
  {
    img: "Blue Jake Pouch Bag.png",
    title: "Blue Jake Pouch Bag",
    category: "acc",
    price: 400,
    avail: true,
  },
  {
    img: "Pink Square Card Holder.png",
    title: "Pink Square Card Holder",
    category: "acc",
    price: 200,
    avail: true,
  },
  {
    img: "Blue Zippered Wallet.png",
    title: "Blue Zippered Wallet",
    category: "acc",
    price: 310,
    avail: true,
  },
  {
    img: "Gold & Yellow Classic Type 7 Watch.png",
    title: "Gold & Yellow Classic Type 7 Watch",
    category: "acc",
    price: 580,
    avail: true,
  },
  {
    img: "Green Padded Tote.png",
    title: "Green Padded Tote",
    category: "acc",
    price: 390,
    avail: true,
  },
  {
    img: "Gunmetal Greca Time Watch.png",
    title: "Gunmetal Greca Time Watch",
    category: "acc",
    price: 450,
    avail: true,
  },
  {
    img: "Khaki Mechanix Edition 1st Camo Gloves.png",
    title: "Khaki Mechanix Edition 1st Camo Gloves",
    category: "acc",
    price: 360,
    avail: true,
  },
  {
    img: "Pink Small Cassette Bag.png",
    title: "Pink Small Cassette Bag",
    category: "acc",
    price: 210,
    avail: true,
  },
  {
    img: "White Logo Socks.png",
    title: "White Logo Socks",
    category: "acc",
    price: 150,
    avail: true,
  },

  {
    img: "Multicolor Vans Edition SK8-HI 38 DX Sneakers.png",
    title: "Multicolor Vans Edition SK8-HI 38 DX Sneakers",
    category: "shoes",
    price: 890,
    avail: true,
  },
  {
    img: "White 327 Sneakers.png",
    title: "White 327 Sneakers",
    category: "shoes",
    price: 400,
    avail: true,
  },
  {
    img: "Green Studded Clogs.png",
    title: "Green Studded Clogs",
    category: "shoes",
    price: 350,
    avail: true,
  },
  {
    img: "White Logo Ankle Boots.png",
    title: "White Logo Ankle Boots",
    category: "shoes",
    price: 600,
    avail: true,
  },
  {
    img: "Green Lido Mules.png",
    title: "Green Lido Mules",
    category: "shoes",
    price: 575,
    avail: true,
  },
  {
    img: "Beige Gucci High Sneakers.png",
    title: "Beige Gucci High Sneakers",
    category: "shoes",
    price: 1120,
    avail: true,
  },
  {
    img: "Brown Chuck 70 Seasonal Color Sneakers.png",
    title: "Brown Chuck 70 Seasonal Color Sneakers",
    category: "shoes",
    price: 460,
    avail: true,
  },
  {
    img: "Blue 'norda 001' RZ Sneakers.png",
    title: "Blue 'norda 001' RZ Sneakers",
    category: "shoes",
    price: 395,
    avail: true,
  },
  {
    img: "Beige Snake Ankle Boots.png",
    title: "Beige Snake Ankle Boots",
    category: "shoes",
    price: 430,
    avail: true,
  },
  {
    img: "Beige Air Jordan 1 Mid SE Craft Sneakers.png",
    title: "Beige Air Jordan 1 Mid SE Craft Sneakers",
    category: "shoes",
    price: 790,
    avail: true,
  },
  {
    img: "Black OG Sk8-Hi LX Sneakers.png",
    title: "Black OG Sk8-Hi LX Sneakers",
    category: "shoes",
    price: 800,
    avail: true,
  },
  {
    img: "Blue Cheope Heeled Mules.png",
    title: "Blue Cheope Heeled Mules",
    category: "shoes",
    price: 640,
    avail: true,
  },
]